### ISSUE TITLE
 quant_ptq is not supported

### ISSUE THREAD

**Issue by wangshankun** [ModelTC/United-Perception#29]
```
root@597e1d20794c:~/EOD# python -u -m up train --ng=1 --launch=pytorch --config=/root/EOD/configs/quant/det/faster_rcnn/faster_rcnn_r18_FPN_2x_quant_qdrop.yaml --display=10 
NOTE! Installing ujson may make loading annotations faster.
No module named 'petrel_client'
init petrel failed
2022-07-14 10:31:18,453-rk0-normalize.py#44:import error No module named 'msbench'; If you need Msbench to prune model,     you should add Msbench to this project. Or just ignore this error.
No module named 'spring_aux'
2022-07-14 10:31:18,758-rk0-spconv_backbone.py#17:import error No module named 'spconv'; If you need spconv, you should install spconv !!!. Or just ignore this error
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/EOD/up/__main__.py", line 27, in <module>
    main()
  File "/root/EOD/up/__main__.py", line 21, in main
    args.run(args)
  File "/root/EOD/up/commands/train.py", line 144, in _main
    launch(main, args.num_gpus_per_machine, args.num_machines, args=args, start_method=args.fork_method)
  File "/root/EOD/up/utils/env/launch.py", line 68, in launch
    main_func(*(args,))
  File "/root/EOD/up/commands/train.py", line 134, in main
    runner = RUNNER_REGISTRY.get(runner_cfg['type'])(cfg, **runner_cfg['kwargs'])
  File "/root/EOD/up/utils/general/registry.py", line 81, in get
    assert module_name in self, '{} is not supported, avaiables are:{}'.format(module_name, self)
AssertionError: quant_ptq is not supported, avaiables are:{'base': <class 'up.runner.base_runner.BaseRunner'>, 'kd': <class 'up.tasks.distill.runner.kd_runner.KDRunner'>, 'point': <class 'up.tasks.det_3d.runner.point_runner.PointRunner'>, 'quant': <class 'up.tasks.quant.runner.quant_runner.QuantRunner'>, 'multitask': <class 'up.tasks.multitask.runner.multitask_runner.MultiTaskRunner'>, 'sparse': <class 'up.tasks.sparse.runner.sparse_runner.SparseRunner'>}
```

**Comment by yqyao** [comment]
Sorry for this bug, the config is not updated, you can replace quant_ptq with quant. @wangshankun
