### ISSUE TITLE
请问这个框架不支持蒸馏吗？

### ISSUE THREAD

**Issue by ersanliqiao** [ModelTC/United-Perception#52]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/juicefs_hz_cv_v3/11105507/AAAI2022/united-perception2/up/__main__.py", line 31, in <module>
    main()
  File "/data/juicefs_hz_cv_v3/11105507/AAAI2022/united-perception2/up/__main__.py", line 25, in main
    args.run(args)
  File "/data/juicefs_hz_cv_v3/11105507/AAAI2022/united-perception2/up/commands/train.py", line 161, in _main
    launch(main, args.num_gpus_per_machine, args.num_machines, args=args, start_method=args.fork_method)
  File "/data/juicefs_hz_cv_v3/11105507/AAAI2022/united-perception2/up/utils/env/launch.py", line 68, in launch
    main_func(*(args,))
  File "/data/juicefs_hz_cv_v3/11105507/AAAI2022/united-perception2/up/commands/train.py", line 140, in main
    runner = RUNNER_REGISTRY.get(runner_cfg['type'])(cfg, **runner_cfg['kwargs'])
  File "/data/juicefs_hz_cv_v3/11105507/AAAI2022/united-perception2/up/utils/general/registry.py", line 81, in get
    assert module_name in self, '{} is not supported, avaiables are:{}'.format(module_name, self)
AssertionError: kd is not supported, avaiables are:{'base': <class 'up.runner.base_runner.BaseRunner'>}

**Comment by yqyao** [comment]
If you want to use distill, you need add tasks export DEFAULT_TASKS=cls:distill @ersanliqiao

**Comment by ersanliqiao** [comment]
> If you want to use distill, you need add tasks export DEFAULT_TASKS=cls:distill @ersanliqiao

多谢，改完可以跑了，另外，想问下我跑nas，导入task也改了（export DEFAULT_TASKS=cls:bignas
），但是还是报错：
no custom work to be done.
+ export DEFAULT_TASKS=cls:bignas
+ DEFAULT_TASKS=cls:bignas
+ bash scripts/dist_train.sh 1 /data/juicefs_hz_cv_v3/11105507/AAAI2022/united-perception2/configs/nas/bignas/cls/bignas_regnet_800m_train_supnet.yaml
No module named 'petrel_client'
init petrel failed
No module named 'spring_aux'
2022-12-06 17:40:51,629-rk0-normalize.py#37:import error No module named 'mqbench'; If you need Mqbench to quantize model,      you should add Mqbench to this project. Or just ignore this error.
2022-12-06 17:40:51,629-rk0-normalize.py#44:import error No module named 'msbench'; If you need Msbench to prune model,     you should add Msbench to this project. Or just ignore this error.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/juicefs_hz_cv_v3/11105507/AAAI2022/united-perception2/up/__main__.py", line 31, in <module>
    main()
  File "/data/juicefs_hz_cv_v3/11105507/AAAI2022/united-perception2/up/__main__.py", line 25, in main
    args.run(args)
  File "/data/juicefs_hz_cv_v3/11105507/AAAI2022/united-perception2/up/commands/train.py", line 161, in _main
    launch(main, args.num_gpus_per_machine, args.num_machines, args=args, start_method=args.fork_method)
  File "/data/juicefs_hz_cv_v3/11105507/AAAI2022/united-perception2/up/utils/env/launch.py", line 68, in launch
    main_func(*(args,))
  File "/data/juicefs_hz_cv_v3/11105507/AAAI2022/united-perception2/up/commands/train.py", line 140, in main
    runner = RUNNER_REGISTRY.get(runner_cfg['type'])(cfg, **runner_cfg['kwargs'])
  File "/data/juicefs_hz_cv_v3/11105507/AAAI2022/united-perception2/up/utils/general/registry.py", line 81, in get
    assert module_name in self, '{} is not supported, avaiables are:{}'.format(module_name, self)
AssertionError: bignas is not supported, avaiables are:{'base': <class 'up.runner.base_runner.BaseRunner'>}
train <class 'up.commands.train.Train'>

**Comment by yqyao** [comment]
Maybe you need  to set DEFAULT_TASKS=cls:nas @ersanliqiao

**Comment by TheWangYang** [comment]
Why did I add export DEFAULT_TASKS=cls:distill as you mentioned above, but I got the following error:
```
ImportError: cannot import name 'gpu_iou_overlap' from 'up.extensions' (/ssd3/wyy/projects/United-Perception/up/extensions/__init__.py)
```
This seems to be the same as the error I reported before when I did not export any tasks. How can I solve it? Looking forward to your reply? @yqyao

**Comment by yqyao** [comment]
If you want to use advanced features,  maybe you need to compile extensions.  following the docs @TheWangYang
